### ISSUE TITLE
FSAttn implementation in plain pytorch?

### ISSUE THREAD

**Issue by neosr-project** [zononhzy/LAMNet#2]
Hi, thanks for your research.
Do you plan on releasing a plain pytorch version of the `FSAttn`? While CUDA kernels are more efficient, there are deployment limitations while using it, which difficults the adoption of this project.

Thanks in advance.

**Comment by zononhzy** [comment]
Thank you for your interest in my work and for raising this question! 😊

Implementing FSAttn with plain PyTorch is indeed possible, but it involves significant complexity. Additionally, such an implementation would result in slower runtime and higher memory usage, which is why I initially opted not to pursue this approach during the design phase.

That said, I understand that deployment limitations with custom CUDA kernels can be challenging. I’ll try to find some time to implement a plain PyTorch version as an alternative for users who may benefit from it. 

Thank you again for your feedback and support!

**Comment by neosr-project** [comment]
Thanks zononhzy!
